// Vocab Barista — 수능/모의고사 기출 어휘 데이터 (2014~2027 수능+6·9월 모의 문제지 32개 추출·생성)
// {w,m,ex,s} 구조, window.wordDataCsat 로 노출 (index.html 카테고리=수능)

window.wordDataCsat = {
    easy: [
        {w: "music", m: "음악", ex: "She listens to classical music while studying.", s: "수능·모의 기출"},
        {w: "right", m: "권리; 옳은", ex: "Everyone has the right to speak freely.", s: "수능·모의 기출"},
        {w: "experience", m: "경험", ex: "Travel gives you valuable life experience.", s: "수능·모의 기출"},
        {w: "person", m: "사람", ex: "She is a very kind person.", s: "수능·모의 기출"},
        {w: "science", m: "과학", ex: "Modern science has changed our daily lives.", s: "수능·모의 기출"},
        {w: "think", m: "생각하다", ex: "I think we should leave now.", s: "수능·모의 기출"},
        {w: "children", m: "아이들", ex: "The children played happily in the park.", s: "수능·모의 기출"},
        {w: "nature", m: "자연; 본성", ex: "We should protect nature for future generations.", s: "수능·모의 기출"},
        {w: "animals", m: "동물들", ex: "Wild animals live in the forest.", s: "수능·모의 기출"},
        {w: "always", m: "항상", ex: "She always arrives early for class.", s: "수능·모의 기출"},
        {w: "found", m: "찾았다; 설립하다", ex: "They found the lost keys under the sofa.", s: "수능·모의 기출"},
        {w: "family", m: "가족", ex: "My family gathers for dinner every Sunday.", s: "수능·모의 기출"},
        {w: "making", m: "만드는 것", ex: "She is good at making decisions.", s: "수능·모의 기출"},
        {w: "three", m: "셋, 3", ex: "There are three books on the desk.", s: "수능·모의 기출"},
        {w: "writing", m: "글쓰기", ex: "Good writing takes years of practice.", s: "수능·모의 기출"},
        {w: "never", m: "결코 ~않다", ex: "I never eat breakfast in the morning.", s: "수능·모의 기출"},
        {w: "learning", m: "학습, 배움", ex: "Learning new skills keeps the mind active.", s: "수능·모의 기출"},
        {w: "groups", m: "집단, 그룹들", ex: "Students worked in small groups.", s: "수능·모의 기출"},
        {w: "something", m: "어떤 것", ex: "I want to tell you something important.", s: "수능·모의 기출"},
        {w: "really", m: "정말로", ex: "I really enjoyed the concert last night.", s: "수능·모의 기출"},
        {w: "understand", m: "이해하다", ex: "I don't understand this math problem.", s: "수능·모의 기출"},
        {w: "still", m: "여전히; 가만히", ex: "She is still waiting for the bus.", s: "수능·모의 기출"},
        {w: "water", m: "물", ex: "Drink plenty of water every day.", s: "수능·모의 기출"},
        {w: "sometimes", m: "때때로", ex: "Sometimes I walk to work.", s: "수능·모의 기출"},
        {w: "thought", m: "생각", ex: "A sudden thought crossed her mind.", s: "수능·모의 기출"},
        {w: "activities", m: "활동들", ex: "The club offers many outdoor activities.", s: "수능·모의 기출"},
        {w: "class", m: "수업; 계층", ex: "Our English class starts at nine.", s: "수능·모의 기출"},
        {w: "times", m: "시대; ~배", ex: "He has visited Paris three times.", s: "수능·모의 기출"},
        {w: "later", m: "나중에", ex: "I'll call you back later today.", s: "수능·모의 기출"},
        {w: "learn", m: "배우다", ex: "Children learn quickly through play.", s: "수능·모의 기출"},
        {w: "asked", m: "물었다, 요청했다", ex: "She asked me for directions.", s: "수능·모의 기출"},
        {w: "thinking", m: "생각, 사고", ex: "Critical thinking is an important skill.", s: "수능·모의 기출"},
        {w: "story", m: "이야기", ex: "Grandma told us a bedtime story.", s: "수능·모의 기출"},
        {w: "words", m: "단어들, 말", ex: "Choose your words carefully.", s: "수능·모의 기출"},
        {w: "products", m: "제품들", ex: "The store sells local products.", s: "수능·모의 기출"},
        {w: "skills", m: "기술, 능력", ex: "Communication skills are essential at work.", s: "수능·모의 기출"},
        {w: "looking", m: "보는 것; 찾는", ex: "She is looking for a new job.", s: "수능·모의 기출"},
        {w: "language", m: "언어", ex: "English is a global language.", s: "수능·모의 기출"},
        {w: "game", m: "게임, 경기", ex: "They watched the football game together.", s: "수능·모의 기출"},
        {w: "possible", m: "가능한", ex: "Please reply as soon as possible.", s: "수능·모의 기출"},
        {w: "called", m: "불렀다, ~라고 불리는", ex: "A group of wolves is called a pack.", s: "수능·모의 기출"},
        {w: "members", m: "구성원들, 회원", ex: "All club members attended the meeting.", s: "수능·모의 기출"},
        {w: "course", m: "과정, 강좌", ex: "I signed up for a cooking course.", s: "수능·모의 기출"},
        {w: "plants", m: "식물들", ex: "Plants need sunlight to grow.", s: "수능·모의 기출"},
        {w: "business", m: "사업, 업무", ex: "She started her own online business.", s: "수능·모의 기출"},
        {w: "future", m: "미래", ex: "We must plan for the future.", s: "수능·모의 기출"},
        {w: "market", m: "시장", ex: "The company entered a new market.", s: "수능·모의 기출"},
        {w: "problems", m: "문제들", ex: "We solved all the problems together.", s: "수능·모의 기출"},
        {w: "program", m: "프로그램, 계획", ex: "The TV program was very informative.", s: "수능·모의 기출"},
        {w: "child", m: "아이", ex: "The child laughed at the clown.", s: "수능·모의 기출"},
        {w: "order", m: "주문; 순서; 명령", ex: "Please put the books in order.", s: "수능·모의 기출"},
        {w: "university", m: "대학교", ex: "She studies biology at university.", s: "수능·모의 기출"},
        {w: "building", m: "건물; 짓기", ex: "The tallest building stands downtown.", s: "수능·모의 기출"},
        {w: "became", m: "~이 되었다", ex: "He became a famous writer.", s: "수능·모의 기출"},
        {w: "since", m: "~이래로; ~때문에", ex: "I have lived here since 2010.", s: "수능·모의 기출"},
        {w: "known", m: "알려진", ex: "He is known for his kindness.", s: "수능·모의 기출"},
        {w: "having", m: "가지는 것", ex: "Having a plan makes work easier.", s: "수능·모의 기출"},
        {w: "woman", m: "여자", ex: "The woman waved at her friend.", s: "수능·모의 기출"},
        {w: "already", m: "이미, 벌써", ex: "They have already finished dinner.", s: "수능·모의 기출"},
        {w: "history", m: "역사", ex: "We studied ancient history in class.", s: "수능·모의 기출"},
        {w: "hours", m: "시간(들)", ex: "He worked for eight hours yesterday.", s: "수능·모의 기출"},
        {w: "ideas", m: "아이디어, 생각들", ex: "She shared her creative ideas.", s: "수능·모의 기출"},
        {w: "space", m: "공간; 우주", ex: "There is not enough space in the room.", s: "수능·모의 기출"},
        {w: "needs", m: "필요, 요구", ex: "The company meets customers' needs.", s: "수능·모의 기출"},
        {w: "higher", m: "더 높은", ex: "Prices are higher during the holidays.", s: "수능·모의 기출"},
        {w: "visit", m: "방문하다", ex: "We plan to visit the museum tomorrow.", s: "수능·모의 기출"},
        {w: "difficult", m: "어려운", ex: "This puzzle is quite difficult.", s: "수능·모의 기출"},
        {w: "countries", m: "국가들", ex: "Many countries signed the agreement.", s: "수능·모의 기출"},
        {w: "scientists", m: "과학자들", ex: "Scientists discovered a new planet.", s: "수능·모의 기출"},
        {w: "books", m: "책들", ex: "She borrowed three books from the library.", s: "수능·모의 기출"},
        {w: "enjoy", m: "즐기다", ex: "I enjoy reading on rainy days.", s: "수능·모의 기출"},
        {w: "activity", m: "활동", ex: "Swimming is a great physical activity.", s: "수능·모의 기출"},
        {w: "health", m: "건강", ex: "Good sleep improves your health.", s: "수능·모의 기출"},
        {w: "changes", m: "변화들", ex: "The seasons bring many changes.", s: "수능·모의 기출"},
        {w: "online", m: "온라인의", ex: "I bought the ticket online.", s: "수능·모의 기출"},
        {w: "website", m: "웹사이트", ex: "Visit our website for more information.", s: "수능·모의 기출"},
        {w: "until", m: "~까지", ex: "Wait here until I come back.", s: "수능·모의 기출"},
        {w: "price", m: "가격", ex: "The price of coffee has risen.", s: "수능·모의 기출"},
        {w: "makes", m: "만들다, ~하게 하다", ex: "Music makes me feel relaxed.", s: "수능·모의 기출"},
        {w: "someone", m: "누군가", ex: "Someone left an umbrella here.", s: "수능·모의 기출"},
        {w: "everyone", m: "모두, 모든 사람", ex: "Everyone enjoyed the party.", s: "수능·모의 기출"},
        {w: "working", m: "일하는; 작동하는", ex: "He is working on a new project.", s: "수능·모의 기출"},
        {w: "came", m: "왔다", ex: "She came home late last night.", s: "수능·모의 기출"},
        {w: "share", m: "공유하다; 몫", ex: "Let's share the pizza equally.", s: "수능·모의 기출"},
        {w: "film", m: "영화; 필름", ex: "The film received great reviews.", s: "수능·모의 기출"},
        {w: "early", m: "이른, 일찍", ex: "She woke up early this morning.", s: "수능·모의 기출"},
        {w: "service", m: "서비스, 봉사", ex: "The hotel offers excellent service.", s: "수능·모의 기출"},
        {w: "product", m: "제품", ex: "This product sells very well.", s: "수능·모의 기출"},
        {w: "together", m: "함께", ex: "We solved the problem together.", s: "수능·모의 기출"},
        {w: "services", m: "서비스들", ex: "The bank offers online services.", s: "수능·모의 기출"},
        {w: "friends", m: "친구들", ex: "She made new friends at school.", s: "수능·모의 기출"},
        {w: "forms", m: "형태들; 양식", ex: "Water exists in three forms.", s: "수능·모의 기출"},
        {w: "trees", m: "나무들", ex: "Tall trees lined the street.", s: "수능·모의 기출"},
        {w: "power", m: "힘, 권력; 전력", ex: "The storm knocked out the power.", s: "수능·모의 기출"},
        {w: "started", m: "시작했다", ex: "The concert started at eight.", s: "수능·모의 기출"},
        {w: "reading", m: "독서, 읽기", ex: "Reading before bed helps me relax.", s: "수능·모의 기출"},
        {w: "animal", m: "동물", ex: "The dog is a loyal animal.", s: "수능·모의 기출"},
        {w: "quickly", m: "빠르게", ex: "She finished the test quickly.", s: "수능·모의 기출"},
        {w: "cannot", m: "~할 수 없다", ex: "I cannot solve this problem alone.", s: "수능·모의 기출"},
        {w: "start", m: "시작하다", ex: "Let's start the meeting now.", s: "수능·모의 기출"},
        {w: "level", m: "수준, 단계", ex: "Her English is at an advanced level.", s: "수능·모의 기출"},
        {w: "events", m: "사건, 행사들", ex: "The city hosts many cultural events.", s: "수능·모의 기출"},
        {w: "shows", m: "보여주다; 프로그램", ex: "The graph shows a clear trend.", s: "수능·모의 기출"},
        {w: "event", m: "사건, 행사", ex: "The wedding was a joyful event.", s: "수능·모의 기출"},
        {w: "night", m: "밤", ex: "The stars shine bright at night.", s: "수능·모의 기출"},
        {w: "enough", m: "충분한", ex: "We have enough food for everyone.", s: "수능·모의 기출"},
        {w: "phone", m: "전화", ex: "She answered the phone quickly.", s: "수능·모의 기출"},
        {w: "larger", m: "더 큰", ex: "We moved to a larger apartment.", s: "수능·모의 기출"},
        {w: "areas", m: "지역들, 분야", ex: "The park covers large areas.", s: "수능·모의 기출"},
        {w: "project", m: "프로젝트, 계획", ex: "We finished the science project on time.", s: "수능·모의 기출"},
        {w: "second", m: "두 번째; 초", ex: "She won second place in the race.", s: "수능·모의 기출"},
        {w: "works", m: "작품들; 작동하다", ex: "The museum displays famous works.", s: "수능·모의 기출"},
        {w: "sounds", m: "소리들; ~처럼 들리다", ex: "That plan sounds great to me.", s: "수능·모의 기출"},
        {w: "believe", m: "믿다", ex: "I believe you can do it.", s: "수능·모의 기출"},
        {w: "special", m: "특별한", ex: "Today is a very special day.", s: "수능·모의 기출"},
        {w: "using", m: "사용하는 것", ex: "She solved it using a simple trick.", s: "수능·모의 기출"},
        {w: "young", m: "어린, 젊은", ex: "The young boy loves drawing.", s: "수능·모의 기출"},
        {w: "meeting", m: "회의, 만남", ex: "The meeting starts at ten sharp.", s: "수능·모의 기출"},
        {w: "usually", m: "보통, 대개", ex: "I usually drink coffee in the morning.", s: "수능·모의 기출"},
        {w: "began", m: "시작했다", ex: "The rain began early this morning.", s: "수능·모의 기출"},
        {w: "sports", m: "스포츠, 운동", ex: "He plays several sports at school.", s: "수능·모의 기출"},
        {w: "places", m: "장소들", ex: "We visited many famous places.", s: "수능·모의 기출"},
        {w: "sound", m: "소리", ex: "I heard a strange sound outside.", s: "수능·모의 기출"},
        {w: "reason", m: "이유", ex: "There is a good reason for the delay.", s: "수능·모의 기출"},
        {w: "living", m: "생활; 살아있는", ex: "The cost of living has risen sharply.", s: "수능·모의 기출"},
        {w: "doing", m: "하는 것", ex: "What are you doing this weekend?", s: "수능·모의 기출"},
        {w: "company", m: "회사; 동행", ex: "She works for a large company.", s: "수능·모의 기출"},
        {w: "center", m: "중심, 센터", ex: "Meet me at the shopping center.", s: "수능·모의 기출"},
        {w: "spent", m: "소비했다, 보냈다", ex: "We spent the afternoon at the beach.", s: "수능·모의 기출"},
        {w: "taking", m: "가져가는 것", ex: "He is taking a break right now.", s: "수능·모의 기출"},
        {w: "strong", m: "강한", ex: "He has a strong sense of duty.", s: "수능·모의 기출"},
        {w: "questions", m: "질문들", ex: "Feel free to ask any questions.", s: "수능·모의 기출"},
        {w: "bring", m: "가져오다", ex: "Please bring your own lunch.", s: "수능·모의 기출"},
        {w: "seems", m: "~처럼 보이다", ex: "She seems happy with the result.", s: "수능·모의 기출"},
        {w: "getting", m: "얻는 것, ~해지는 것", ex: "It's getting dark outside.", s: "수능·모의 기출"},
        {w: "lives", m: "삶, 생명들; 살다", ex: "The discovery changed many lives.", s: "수능·모의 기출"},
        {w: "stories", m: "이야기들", ex: "He tells funny stories at parties.", s: "수능·모의 기출"},
        {w: "video", m: "비디오, 영상", ex: "She posted a video online.", s: "수능·모의 기출"},
        {w: "close", m: "가까운; 닫다", ex: "My house is close to the station.", s: "수능·모의 기출"},
        {w: "friend", m: "친구", ex: "My best friend lives next door.", s: "수능·모의 기출"},
        {w: "games", m: "게임들, 경기들", ex: "The children played board games.", s: "수능·모의 기출"},
        {w: "lower", m: "더 낮은; 낮추다", ex: "Prices are lower in the morning.", s: "수능·모의 기출"},
        {w: "concert", m: "콘서트, 음악회", ex: "We attended a jazz concert.", s: "수능·모의 기출"},
        {w: "mother", m: "어머니", ex: "My mother cooks delicious food.", s: "수능·모의 기출"},
        {w: "playing", m: "노는 것, 연주하는 것", ex: "The kids are playing in the yard.", s: "수능·모의 기출"},
        {w: "office", m: "사무실", ex: "He works in a downtown office.", s: "수능·모의 기출"},
        {w: "longer", m: "더 긴, 더 오래", ex: "The trip took longer than expected.", s: "수능·모의 기출"},
        {w: "kids", m: "아이들", ex: "The kids love the new playground.", s: "수능·모의 기출"},
        {w: "picture", m: "그림, 사진", ex: "She drew a beautiful picture.", s: "수능·모의 기출"},
        {w: "looked", m: "보았다", ex: "He looked out the window.", s: "수능·모의 기출"},
        {w: "parents", m: "부모", ex: "My parents support my dreams.", s: "수능·모의 기출"},
        {w: "table", m: "탁자; 표", ex: "Dinner is ready on the table.", s: "수능·모의 기출"},
        {w: "rules", m: "규칙들", ex: "Please follow the safety rules.", s: "수능·모의 기출"},
        {w: "choice", m: "선택", ex: "You made the right choice.", s: "수능·모의 기출"},
        {w: "fish", m: "물고기, 생선", ex: "We caught three fish in the lake.", s: "수능·모의 기출"},
        {w: "clear", m: "명확한; 맑은", ex: "The sky is clear and blue today.", s: "수능·모의 기출"},
        {w: "smaller", m: "더 작은", ex: "We need a smaller table.", s: "수능·모의 기출"},
        {w: "along", m: "~을 따라", ex: "We walked along the beach.", s: "수능·모의 기출"},
        {w: "goal", m: "목표; 골", ex: "Her goal is to become a doctor.", s: "수능·모의 기출"},
        {w: "eyes", m: "눈(들)", ex: "She has bright blue eyes.", s: "수능·모의 기출"},
        {w: "summer", m: "여름", ex: "We swim a lot in summer.", s: "수능·모의 기출"},
        {w: "almost", m: "거의", ex: "We are almost finished with the project.", s: "수능·모의 기출"},
        {w: "money", m: "돈", ex: "He saved money for a new bike.", s: "수능·모의 기출"},
        {w: "easily", m: "쉽게", ex: "She learns new songs easily.", s: "수능·모의 기출"},
        {w: "ones", m: "것들", ex: "I like the red ones better.", s: "수능·모의 기출"},
        {w: "choose", m: "선택하다", ex: "You may choose any color you like.", s: "수능·모의 기출"},
        {w: "walking", m: "걷기", ex: "Walking is good for your health.", s: "수능·모의 기출"},
        {w: "feeling", m: "느낌, 감정", ex: "I have a good feeling about this.", s: "수능·모의 기출"},
        {w: "outside", m: "밖에, 바깥", ex: "The children played outside all day.", s: "수능·모의 기출"},
        {w: "thanks", m: "감사", ex: "Thanks for your kind help.", s: "수능·모의 기출"},
        {w: "allowed", m: "허용된", ex: "Pets are not allowed inside.", s: "수능·모의 기출"},
        {w: "finally", m: "마침내", ex: "We finally reached the summit.", s: "수능·모의 기출"},
        {w: "leaves", m: "나뭇잎들; 떠나다", ex: "The leaves turn red in autumn.", s: "수능·모의 기출"},
        {w: "front", m: "앞", ex: "He parked in front of the house.", s: "수능·모의 기출"},
        {w: "watch", m: "보다; 손목시계", ex: "Let's watch a movie tonight.", s: "수능·모의 기출"},
        {w: "remember", m: "기억하다", ex: "Remember to lock the door.", s: "수능·모의 기출"},
        {w: "green", m: "초록색의", ex: "The garden is full of green plants.", s: "수능·모의 기출"},
        {w: "learned", m: "배웠다", ex: "She learned to swim last summer.", s: "수능·모의 기출"},
        {w: "becomes", m: "~이 되다", ex: "Ice becomes water when it melts.", s: "수능·모의 기출"},
        {w: "nothing", m: "아무것도 아닌 것", ex: "There is nothing left in the fridge.", s: "수능·모의 기출"},
        {w: "father", m: "아버지", ex: "My father teaches at a high school.", s: "수능·모의 기출"},
        {w: "forest", m: "숲", ex: "Many animals live in the forest.", s: "수능·모의 기출"},
        {w: "birds", m: "새들", ex: "Birds sing early in the morning.", s: "수능·모의 기출"},
        {w: "born", m: "태어난", ex: "She was born in Seoul.", s: "수능·모의 기출"},
        {w: "library", m: "도서관", ex: "I study at the library every day.", s: "수능·모의 기출"},
        {w: "results", m: "결과들", ex: "The test results came out today.", s: "수능·모의 기출"},
        {w: "check", m: "확인하다; 수표", ex: "Please check your answers again.", s: "수능·모의 기출"},
        {w: "feelings", m: "감정, 느낌들", ex: "Don't hide your true feelings.", s: "수능·모의 기출"},
        {w: "reasons", m: "이유들", ex: "She gave several reasons for leaving.", s: "수능·모의 기출"},
        {w: "yourself", m: "너 자신", ex: "Believe in yourself and try again.", s: "수능·모의 기출"},
        {w: "follow", m: "따르다", ex: "Please follow the instructions carefully.", s: "수능·모의 기출"},
        {w: "comes", m: "오다", ex: "Spring comes after winter.", s: "수능·모의 기출"},
        {w: "college", m: "대학", ex: "He plans to attend college next year.", s: "수능·모의 기출"},
        {w: "question", m: "질문", ex: "May I ask you a question?", s: "수능·모의 기출"},
        {w: "speed", m: "속도", ex: "He drove at high speed.", s: "수능·모의 기출"},
        {w: "internet", m: "인터넷", ex: "I use the internet for research.", s: "수능·모의 기출"},
        {w: "beautiful", m: "아름다운", ex: "The sunset was truly beautiful.", s: "수능·모의 기출"},
        {w: "spend", m: "쓰다, 소비하다", ex: "I spend too much time online.", s: "수능·모의 기출"},
        {w: "trying", m: "노력하는 것", ex: "She is trying her best to improve.", s: "수능·모의 기출"},
        {w: "days", m: "날들, 나날", ex: "These days I feel very busy.", s: "수능·모의 기출"},
        {w: "color", m: "색깔", ex: "Blue is my favorite color.", s: "수능·모의 기출"},
        {w: "everything", m: "모든 것", ex: "Everything went according to plan.", s: "수능·모의 기출"},
        {w: "companies", m: "회사들", ex: "Many companies now work remotely.", s: "수능·모의 기출"},
        {w: "baseball", m: "야구", ex: "He plays baseball every weekend.", s: "수능·모의 기출"},
        {w: "message", m: "메시지", ex: "I left a message on her phone.", s: "수능·모의 기출"},
        {w: "moving", m: "움직이는; 감동적인", ex: "The moving train sped past us.", s: "수능·모의 기출"},
        {w: "light", m: "빛; 가벼운", ex: "Sunlight streamed through the window.", s: "수능·모의 기출"},
        {w: "types", m: "유형, 종류들", ex: "There are many types of birds.", s: "수능·모의 기출"},
        {w: "shared", m: "공유된", ex: "They shared the same dream.", s: "수능·모의 기출"},
        {w: "difference", m: "차이", ex: "There is a big difference between them.", s: "수능·모의 기출"},
        {w: "whole", m: "전체의", ex: "She ate the whole cake.", s: "수능·모의 기출"},
        {w: "eating", m: "먹는 것", ex: "Eating slowly aids digestion.", s: "수능·모의 기출"},
        {w: "growing", m: "자라는, 커지는", ex: "There is a growing interest in art.", s: "수능·모의 기출"},
        {w: "written", m: "쓰여진", ex: "The letter was written in French.", s: "수능·모의 기출"},
        {w: "worry", m: "걱정하다", ex: "Don't worry about the test.", s: "수능·모의 기출"},
        {w: "painting", m: "그림, 회화", ex: "She admired the famous painting.", s: "수능·모의 기출"},
        {w: "store", m: "가게; 저장하다", ex: "I bought milk at the store.", s: "수능·모의 기출"},
        {w: "computer", m: "컴퓨터", ex: "My computer is running slowly.", s: "수능·모의 기출"},
        {w: "gift", m: "선물; 재능", ex: "She has a gift for music.", s: "수능·모의 기출"},
        {w: "house", m: "집", ex: "They live in a small house.", s: "수능·모의 기출"},
        {w: "perfect", m: "완벽한", ex: "The weather is perfect for a picnic.", s: "수능·모의 기출"},
        {w: "minutes", m: "분(들)", ex: "The class ends in ten minutes.", s: "수능·모의 기출"},
        {w: "black", m: "검은색의", ex: "He wore a black jacket.", s: "수능·모의 기출"},
        {w: "white", m: "흰색의", ex: "The walls are painted white.", s: "수능·모의 기출"},
        {w: "highest", m: "가장 높은", ex: "Mount Everest is the highest peak.", s: "수능·모의 기출"},
        {w: "waiting", m: "기다리는 것", ex: "She is waiting for the bus.", s: "수능·모의 기출"},
        {w: "decided", m: "결정했다", ex: "We decided to go camping.", s: "수능·모의 기출"},
        {w: "birthday", m: "생일", ex: "Happy birthday to you!", s: "수능·모의 기출"},
        {w: "happy", m: "행복한", ex: "She felt happy after the good news.", s: "수능·모의 기출"},
        {w: "wanted", m: "원했다", ex: "He wanted to become a pilot.", s: "수능·모의 기출"},
        {w: "lunch", m: "점심", ex: "Let's have lunch together.", s: "수능·모의 기출"},
        {w: "clearly", m: "분명하게", ex: "Please speak more clearly.", s: "수능·모의 기출"},
        {w: "daily", m: "매일의", ex: "Reading is part of my daily routine.", s: "수능·모의 기출"},
        {w: "dress", m: "드레스; 옷을 입다", ex: "She wore a red dress to the party.", s: "수능·모의 기출"},
        {w: "goals", m: "목표들", ex: "Set clear goals for the year.", s: "수능·모의 기출"},
        {w: "popular", m: "인기 있는", ex: "This song is very popular now.", s: "수능·모의 기출"},
        {w: "plant", m: "식물; 심다", ex: "We plant flowers in spring.", s: "수능·모의 기출"},
        {w: "voice", m: "목소리", ex: "She has a lovely singing voice.", s: "수능·모의 기출"},
        {w: "saying", m: "말하는 것; 속담", ex: "There's an old saying about patience.", s: "수능·모의 기출"},
        {w: "needed", m: "필요했다", ex: "We needed more time to finish.", s: "수능·모의 기출"},
        {w: "turned", m: "돌렸다, 변했다", ex: "She turned the page slowly.", s: "수능·모의 기출"},
        {w: "travel", m: "여행하다; 여행", ex: "I love to travel during holidays.", s: "수능·모의 기출"},
        {w: "paper", m: "종이; 논문", ex: "She wrote a research paper.", s: "수능·모의 기출"},
        {w: "useful", m: "유용한", ex: "This tool is very useful.", s: "수능·모의 기출"},
        {w: "heard", m: "들었다", ex: "I heard the good news yesterday.", s: "수능·모의 기출"},
        {w: "teaching", m: "가르치는 것, 교육", ex: "She loves teaching young children.", s: "수능·모의 기출"},
        {w: "costs", m: "비용들; 비용이 들다", ex: "The trip costs too much money.", s: "수능·모의 기출"},
        {w: "camp", m: "캠프, 야영", ex: "They went to summer camp.", s: "수능·모의 기출"},
        {w: "artist", m: "예술가", ex: "The artist painted a beautiful scene.", s: "수능·모의 기출"},
        {w: "action", m: "행동, 조치", ex: "We must take action now.", s: "수능·모의 기출"},
        {w: "running", m: "달리기; 운영", ex: "Running keeps me fit.", s: "수능·모의 기출"},
        {w: "thoughts", m: "생각들", ex: "Share your thoughts with the group.", s: "수능·모의 기출"},
        {w: "mountain", m: "산", ex: "They climbed the tall mountain.", s: "수능·모의 기출"},
        {w: "takes", m: "걸리다, 가져가다", ex: "It takes an hour to get there.", s: "수능·모의 기출"},
        {w: "sport", m: "스포츠, 운동", ex: "Soccer is a popular sport.", s: "수능·모의 기출"},
        {w: "million", m: "백만", ex: "The city has two million people.", s: "수능·모의 기출"},
        {w: "faces", m: "얼굴들; 직면하다", ex: "The company faces many problems.", s: "수능·모의 기출"},
        {w: "parts", m: "부분들", ex: "The machine has many parts.", s: "수능·모의 기출"},
        {w: "taken", m: "가져간, 취해진", ex: "The photo was taken last year.", s: "수능·모의 기출"},
        {w: "added", m: "더했다, 추가했다", ex: "She added sugar to the tea.", s: "수능·모의 기출"},
        {w: "street", m: "거리, 길", ex: "The shop is on Main Street.", s: "수능·모의 기출"},
        {w: "cars", m: "자동차들", ex: "Electric cars are becoming popular.", s: "수능·모의 기출"},
        {w: "messages", m: "메시지들", ex: "She sent me several messages.", s: "수능·모의 기출"},
        {w: "famous", m: "유명한", ex: "He is a famous movie star.", s: "수능·모의 기출"},
        {w: "buying", m: "사는 것", ex: "She is buying groceries now.", s: "수능·모의 기출"},
        {w: "behind", m: "~뒤에", ex: "The cat hid behind the sofa.", s: "수능·모의 기출"},
        {w: "wrong", m: "틀린, 잘못된", ex: "You dialed the wrong number.", s: "수능·모의 기출"},
        {w: "tools", m: "도구들", ex: "He keeps his tools in the garage.", s: "수능·모의 기출"},
        {w: "short", m: "짧은", ex: "She gave a short speech.", s: "수능·모의 기출"},
        {w: "ages", m: "나이, 시대들", ex: "Children of all ages joined the game.", s: "수능·모의 기출"},
        {w: "ocean", m: "바다, 대양", ex: "The ocean covers most of the earth.", s: "수능·모의 기출"},
        {w: "adults", m: "성인들", ex: "Adults must supervise the children.", s: "수능·모의 기출"},
        {w: "blue", m: "파란색의", ex: "The sky turned deep blue.", s: "수능·모의 기출"},
        {w: "email", m: "이메일", ex: "Please send me an email.", s: "수능·모의 기출"},
        {w: "excited", m: "신난, 흥분한", ex: "The kids were excited about the trip.", s: "수능·모의 기출"},
        {w: "tomorrow", m: "내일", ex: "We will meet again tomorrow.", s: "수능·모의 기출"},
        {w: "tried", m: "시도했다", ex: "He tried hard to fix the car.", s: "수능·모의 기출"},
        {w: "fruit", m: "과일", ex: "Fresh fruit is good for you.", s: "수능·모의 기출"},
        {w: "drive", m: "운전하다; 몰아가다", ex: "I drive to work every day.", s: "수능·모의 기출"},
        {w: "levels", m: "수준들, 단계들", ex: "The course has three difficulty levels.", s: "수능·모의 기출"},
        {w: "moment", m: "순간", ex: "Please wait a moment.", s: "수능·모의 기출"},
        {w: "facts", m: "사실들", ex: "Stick to the facts, please.", s: "수능·모의 기출"},
        {w: "showed", m: "보여주었다", ex: "She showed me her new painting.", s: "수능·모의 기출"},
        {w: "happens", m: "일어나다, 발생하다", ex: "Accidents happen when we rush.", s: "수능·모의 기출"},
        {w: "write", m: "쓰다", ex: "Please write your name here.", s: "수능·모의 기출"},
        {w: "shown", m: "보여진", ex: "The results are shown in the chart.", s: "수능·모의 기출"},
        {w: "smile", m: "미소; 미소짓다", ex: "Her smile lit up the room.", s: "수능·모의 기출"},
        {w: "changed", m: "변했다", ex: "The city has changed a lot.", s: "수능·모의 기출"},
        {w: "clock", m: "시계", ex: "The clock on the wall stopped.", s: "수능·모의 기출"},
        {w: "watching", m: "보는 것", ex: "We spent the evening watching movies.", s: "수능·모의 기출"},
        {w: "festival", m: "축제", ex: "The music festival lasts three days.", s: "수능·모의 기출"},
        {w: "changing", m: "변화하는", ex: "The world is changing fast.", s: "수능·모의 기출"},
        {w: "placed", m: "놓았다, 배치했다", ex: "She placed the vase on the shelf.", s: "수능·모의 기출"},
        {w: "door", m: "문", ex: "Please close the door quietly.", s: "수능·모의 기출"},
        {w: "simple", m: "간단한, 단순한", ex: "The recipe is quick and simple.", s: "수능·모의 기출"},
        {w: "interesting", m: "흥미로운", ex: "That was an interesting story.", s: "수능·모의 기출"},
        {w: "party", m: "파티; 정당", ex: "They threw a surprise party.", s: "수능·모의 기출"},
        {w: "explain", m: "설명하다", ex: "Can you explain this rule?", s: "수능·모의 기출"},
        {w: "earth", m: "지구; 흙", ex: "The earth revolves around the sun.", s: "수능·모의 기출"},
        {w: "drawing", m: "그림, 소묘", ex: "She made a lovely drawing.", s: "수능·모의 기출"},
        {w: "kinds", m: "종류들", ex: "There are many kinds of flowers.", s: "수능·모의 기출"},
        {w: "dream", m: "꿈; 꿈꾸다", ex: "Her dream is to travel the world.", s: "수능·모의 기출"},
        {w: "grow", m: "자라다, 기르다", ex: "Tomatoes grow well in summer.", s: "수능·모의 기출"},
        {w: "becoming", m: "~이 되는 것", ex: "She is becoming a great artist.", s: "수능·모의 기출"},
        {w: "played", m: "놀았다, 연주했다", ex: "The band played all night.", s: "수능·모의 기출"},
        {w: "walked", m: "걸었다", ex: "We walked to the park.", s: "수능·모의 기출"},
        {w: "date", m: "날짜; 데이트", ex: "What is today's date?", s: "수능·모의 기출"},
        {w: "prize", m: "상, 상품", ex: "She won the first prize.", s: "수능·모의 기출"},
        {w: "replied", m: "대답했다", ex: "He replied to my email quickly.", s: "수능·모의 기출"},
        {w: "sleep", m: "잠; 자다", ex: "I need eight hours of sleep.", s: "수능·모의 기출"},
        {w: "months", m: "달, 개월들", ex: "The project took six months.", s: "수능·모의 기출"},
        {w: "workers", m: "노동자들", ex: "The factory workers went on strike.", s: "수능·모의 기출"},
        {w: "middle", m: "중간, 가운데", ex: "He sat in the middle of the room.", s: "수능·모의 기출"},
        {w: "piece", m: "조각, 부분", ex: "She ate a piece of cake.", s: "수능·모의 기출"},
        {w: "player", m: "선수; 재생기", ex: "He is the best player on the team.", s: "수능·모의 기출"},
        {w: "country", m: "나라; 시골", ex: "Japan is a beautiful country.", s: "수능·모의 기출"},
        {w: "pictures", m: "그림들, 사진들", ex: "She took many pictures on the trip.", s: "수능·모의 기출"},
        {w: "agree", m: "동의하다", ex: "I agree with your opinion.", s: "수능·모의 기출"},
        {w: "helps", m: "돕다", ex: "Exercise helps reduce stress.", s: "수능·모의 기출"},
        {w: "leaving", m: "떠나는 것", ex: "She is leaving for London tomorrow.", s: "수능·모의 기출"},
        {w: "television", m: "텔레비전", ex: "We watched the news on television.", s: "수능·모의 기출"},
        {w: "begin", m: "시작하다", ex: "Let's begin the lesson.", s: "수능·모의 기출"},
        {w: "forests", m: "숲들", ex: "Tropical forests are rich in life.", s: "수능·모의 기출"},
        {w: "arts", m: "예술, 미술", ex: "She studies the fine arts.", s: "수능·모의 기출"},
        {w: "numbers", m: "숫자들", ex: "Write the numbers in order.", s: "수능·모의 기출"},
        {w: "teachers", m: "교사들", ex: "The teachers prepared the lesson.", s: "수능·모의 기출"},
        {w: "glass", m: "유리; 유리잔", ex: "She drank a glass of milk.", s: "수능·모의 기출"},
        {w: "talking", m: "말하는 것", ex: "They were talking about the movie.", s: "수능·모의 기출"},
        {w: "weather", m: "날씨", ex: "The weather is nice today.", s: "수능·모의 기출"},
        {w: "daughter", m: "딸", ex: "Their daughter started school this year.", s: "수능·모의 기출"},
        {w: "songs", m: "노래들", ex: "She sang two songs at the show.", s: "수능·모의 기출"},
        {w: "heart", m: "심장; 마음", ex: "Exercise strengthens your heart.", s: "수능·모의 기출"},
        {w: "coming", m: "오는 것", ex: "Winter is coming soon.", s: "수능·모의 기출"},
        {w: "please", m: "기쁘게 하다; 부디", ex: "Please close the door when you leave.", s: "수능·모의 기출"},
        {w: "sorry", m: "미안한, 유감스러운", ex: "I'm sorry for being late this morning.", s: "수능·모의 기출"},
        {w: "thank", m: "감사하다", ex: "I want to thank you for your help.", s: "수능·모의 기출"},
        {w: "women", m: "여성들(woman의 복수)", ex: "Many women joined the science program.", s: "수능·모의 기출"},
    ],
    normal: [
        {w: "process", m: "과정, 절차", ex: "Learning a language is a slow process.", s: "수능·모의 기출"},
        {w: "self", m: "자아, 자신", ex: "A strong sense of self builds confidence.", s: "수능·모의 기출"},
        {w: "rather", m: "오히려, 다소", ex: "I would rather stay home tonight.", s: "수능·모의 기출"},
        {w: "cultural", m: "문화의", ex: "The festival celebrates cultural diversity.", s: "수능·모의 기출"},
        {w: "public", m: "공공의, 대중의", ex: "The park is open to the public.", s: "수능·모의 기출"},
        {w: "culture", m: "문화", ex: "Food is an important part of culture.", s: "수능·모의 기출"},
        {w: "sense", m: "감각; 의미", ex: "Her words made perfect sense to me.", s: "수능·모의 기출"},
        {w: "behavior", m: "행동", ex: "His polite behavior impressed everyone.", s: "수능·모의 기출"},
        {w: "based", m: "~에 근거한", ex: "The movie is based on a true story.", s: "수능·모의 기출"},
        {w: "media", m: "매체, 미디어", ex: "Social media affects how we communicate.", s: "수능·모의 기출"},
        {w: "system", m: "체계, 시스템", ex: "The transport system is very efficient.", s: "수능·모의 기출"},
        {w: "research", m: "연구, 조사", ex: "Scientists conduct research on climate change.", s: "수능·모의 기출"},
        {w: "provide", m: "제공하다", ex: "The school provides free lunch to students.", s: "수능·모의 기출"},
        {w: "natural", m: "자연의, 천연의", ex: "This soap is made from natural ingredients.", s: "수능·모의 기출"},
        {w: "likely", m: "~할 것 같은", ex: "It is likely to rain this afternoon.", s: "수능·모의 기출"},
        {w: "value", m: "가치; 소중히 여기다", ex: "We value honesty above all else.", s: "수능·모의 기출"},
        {w: "contest", m: "대회, 경연", ex: "He won first place in the contest.", s: "수능·모의 기출"},
        {w: "certain", m: "확실한; 어떤", ex: "I am certain she will succeed.", s: "수능·모의 기출"},
        {w: "although", m: "비록 ~일지라도", ex: "Although it was cold, we went outside.", s: "수능·모의 기출"},
        {w: "species", m: "종(생물)", ex: "Many species are at risk of extinction.", s: "수능·모의 기출"},
        {w: "physical", m: "신체의; 물리적인", ex: "Regular physical activity keeps you healthy.", s: "수능·모의 기출"},
        {w: "ability", m: "능력, 재능", ex: "He has the ability to solve hard problems.", s: "수능·모의 기출"},
        {w: "focus", m: "집중; 초점", ex: "Try to focus on one task at a time.", s: "수능·모의 기출"},
        {w: "result", m: "결과", ex: "The result of the experiment surprised us.", s: "수능·모의 기출"},
        {w: "modern", m: "현대의", ex: "Modern technology changes rapidly.", s: "수능·모의 기출"},
        {w: "create", m: "창조하다, 만들다", ex: "Artists create beautiful works of art.", s: "수능·모의 기출"},
        {w: "society", m: "사회", ex: "Education benefits the whole society.", s: "수능·모의 기출"},
        {w: "whether", m: "~인지 아닌지", ex: "I don't know whether she will come.", s: "수능·모의 기출"},
        {w: "benefits", m: "이익, 혜택", ex: "Exercise has many health benefits.", s: "수능·모의 기출"},
        {w: "control", m: "통제; 조절하다", ex: "He tried to control his temper.", s: "수능·모의 기출"},
        {w: "simply", m: "단순히, 그저", ex: "The recipe is simply too complicated.", s: "수능·모의 기출"},
        {w: "positive", m: "긍정적인", ex: "She always keeps a positive attitude.", s: "수능·모의 기출"},
        {w: "means", m: "수단; 의미하다", ex: "This word means 'happiness' in Korean.", s: "수능·모의 기출"},
        {w: "values", m: "가치관", ex: "Honesty is one of her core values.", s: "수능·모의 기출"},
        {w: "actually", m: "실제로, 사실은", ex: "It's actually easier than it looks.", s: "수능·모의 기출"},
        {w: "personal", m: "개인의, 사적인", ex: "Keep your personal information safe.", s: "수능·모의 기출"},
        {w: "given", m: "주어진", ex: "Complete the task within the given time.", s: "수능·모의 기출"},
        {w: "common", m: "흔한, 공통의", ex: "Colds are common in winter.", s: "수능·모의 기출"},
        {w: "instead", m: "대신에", ex: "Let's walk instead of driving.", s: "수능·모의 기출"},
        {w: "local", m: "지역의, 현지의", ex: "We bought fruit from a local farmer.", s: "수능·모의 기출"},
        {w: "matter", m: "문제; 중요하다", ex: "Your opinion really does matter.", s: "수능·모의 기출"},
        {w: "material", m: "재료, 물질", ex: "Cotton is a soft material.", s: "수능·모의 기출"},
        {w: "various", m: "다양한", ex: "The shop sells various kinds of tea.", s: "수능·모의 기출"},
        {w: "negative", m: "부정적인", ex: "Stress can have negative effects on health.", s: "수능·모의 기출"},
        {w: "century", m: "세기, 100년", ex: "The building dates from the 19th century.", s: "수능·모의 기출"},
        {w: "evidence", m: "증거", ex: "There is no evidence to support that claim.", s: "수능·모의 기출"},
        {w: "present", m: "현재의; 선물; 제시하다", ex: "He gave her a birthday present.", s: "수능·모의 기출"},
        {w: "design", m: "디자인; 설계하다", ex: "They design eco-friendly buildings.", s: "수능·모의 기출"},
        {w: "brain", m: "뇌", ex: "Sleep helps the brain recover.", s: "수능·모의 기출"},
        {w: "objects", m: "물체들; 대상", ex: "The shelf holds many small objects.", s: "수능·모의 기출"},
        {w: "musical", m: "음악의", ex: "She has great musical talent.", s: "수능·모의 기출"},
        {w: "humans", m: "인간들", ex: "Humans need water to survive.", s: "수능·모의 기출"},
        {w: "develop", m: "발전시키다, 개발하다", ex: "They developed a new mobile app.", s: "수능·모의 기출"},
        {w: "training", m: "훈련, 교육", ex: "New employees receive job training.", s: "수능·모의 기출"},
        {w: "economic", m: "경제의", ex: "The country faces economic challenges.", s: "수능·모의 기출"},
        {w: "state", m: "상태; 주(州); 진술하다", ex: "The house is in a poor state.", s: "수능·모의 기출"},
        {w: "consider", m: "고려하다", ex: "Please consider all the options carefully.", s: "수능·모의 기출"},
        {w: "though", m: "비록 ~이지만", ex: "He passed the test, though barely.", s: "수능·모의 기출"},
        {w: "beyond", m: "~을 넘어서", ex: "The mountains lie beyond the river.", s: "수능·모의 기출"},
        {w: "addition", m: "추가; 덧셈", ex: "In addition, we offer free delivery.", s: "수능·모의 기출"},
        {w: "effects", m: "효과, 영향들", ex: "The medicine has few side effects.", s: "수능·모의 기출"},
        {w: "states", m: "상태들; 진술하다", ex: "The report states the main findings.", s: "수능·모의 기출"},
        {w: "field", m: "분야; 들판", ex: "She is an expert in her field.", s: "수능·모의 기출"},
        {w: "itself", m: "그 자체", ex: "The problem will solve itself.", s: "수능·모의 기출"},
        {w: "greater", m: "더 큰, 더 많은", ex: "This task requires greater effort.", s: "수능·모의 기출"},
        {w: "growth", m: "성장", ex: "The company reported rapid growth.", s: "수능·모의 기출"},
        {w: "reality", m: "현실", ex: "Virtual reality feels almost real.", s: "수능·모의 기출"},
        {w: "emotions", m: "감정들", ex: "Music can stir strong emotions.", s: "수능·모의 기출"},
        {w: "industry", m: "산업", ex: "The tech industry creates many jobs.", s: "수능·모의 기출"},
        {w: "waste", m: "낭비하다; 쓰레기", ex: "Don't waste your time on small things.", s: "수능·모의 기출"},
        {w: "complex", m: "복잡한", ex: "The human brain is very complex.", s: "수능·모의 기출"},
        {w: "perhaps", m: "아마도", ex: "Perhaps we should ask for help.", s: "수능·모의 기출"},
        {w: "digital", m: "디지털의", ex: "We live in a digital age.", s: "수능·모의 기출"},
        {w: "requires", m: "요구하다, 필요로 하다", ex: "This job requires great patience.", s: "수능·모의 기출"},
        {w: "support", m: "지지하다; 지원", ex: "Her friends support her every decision.", s: "수능·모의 기출"},
        {w: "decision", m: "결정", ex: "Making a decision can be hard.", s: "수능·모의 기출"},
        {w: "source", m: "근원, 출처", ex: "The sun is our main energy source.", s: "수능·모의 기출"},
        {w: "least", m: "가장 적은, 최소", ex: "Choose the option with the least risk.", s: "수능·모의 기출"},
        {w: "limited", m: "제한된", ex: "Tickets are available in limited numbers.", s: "수능·모의 기출"},
        {w: "cultures", m: "문화들", ex: "Different cultures have unique customs.", s: "수능·모의 기출"},
        {w: "success", m: "성공", ex: "Hard work leads to success.", s: "수능·모의 기출"},
        {w: "similar", m: "비슷한", ex: "The twins have similar personalities.", s: "수능·모의 기출"},
        {w: "graph", m: "그래프, 도표", ex: "The graph shows monthly sales.", s: "수능·모의 기출"},
        {w: "object", m: "물체; 대상; 반대하다", ex: "A strange object appeared in the sky.", s: "수능·모의 기출"},
        {w: "global", m: "세계적인, 지구의", ex: "Climate change is a global issue.", s: "수능·모의 기출"},
        {w: "toward", m: "~쪽으로", ex: "She walked toward the exit.", s: "수능·모의 기출"},
        {w: "quality", m: "질, 품질", ex: "This shop sells high quality goods.", s: "수능·모의 기출"},
        {w: "average", m: "평균; 보통의", ex: "The average score was seventy.", s: "수능·모의 기출"},
        {w: "basic", m: "기본적인", ex: "Everyone needs basic skills to survive.", s: "수능·모의 기출"},
        {w: "offer", m: "제공하다; 제안", ex: "They offer free coffee to guests.", s: "수능·모의 기출"},
        {w: "approach", m: "접근법; 다가가다", ex: "We need a new approach to the problem.", s: "수능·모의 기출"},
        {w: "interest", m: "관심, 흥미; 이자", ex: "She shows great interest in art.", s: "수능·모의 기출"},
        {w: "national", m: "국가의, 전국의", ex: "They won the national championship.", s: "수능·모의 기출"},
        {w: "energy", m: "에너지, 활력", ex: "Solar energy is clean and renewable.", s: "수능·모의 기출"},
        {w: "several", m: "몇몇의", ex: "I visited several countries last year.", s: "수능·모의 기출"},
        {w: "provides", m: "제공하다", ex: "The app provides useful information.", s: "수능·모의 기출"},
        {w: "category", m: "범주, 분류", ex: "This book fits in the fiction category.", s: "수능·모의 기출"},
        {w: "major", m: "주요한; 전공", ex: "Traffic is a major problem in cities.", s: "수능·모의 기출"},
        {w: "terms", m: "용어; 조건들", ex: "Please read the terms carefully.", s: "수능·모의 기출"},
        {w: "response", m: "반응, 응답", ex: "Her response surprised everyone.", s: "수능·모의 기출"},
        {w: "issues", m: "문제들, 쟁점", ex: "We discussed important social issues.", s: "수능·모의 기출"},
        {w: "stress", m: "스트레스; 강조하다", ex: "Too much stress harms your health.", s: "수능·모의 기출"},
        {w: "specific", m: "구체적인, 특정한", ex: "Give me a specific example, please.", s: "수능·모의 기출"},
        {w: "single", m: "단 하나의; 독신의", ex: "Not a single mistake was found.", s: "수능·모의 기출"},
        {w: "factors", m: "요인들", ex: "Many factors affect the outcome.", s: "수능·모의 기출"},
        {w: "insects", m: "곤충들", ex: "Insects play a vital role in nature.", s: "수능·모의 기출"},
        {w: "meaning", m: "의미", ex: "What is the meaning of this word?", s: "수능·모의 기출"},
        {w: "unique", m: "독특한, 유일한", ex: "Every snowflake has a unique shape.", s: "수능·모의 기출"},
        {w: "impact", m: "영향, 충격", ex: "The news had a big impact on us.", s: "수능·모의 기출"},
        {w: "period", m: "기간; 시기", ex: "He rested for a short period.", s: "수능·모의 기출"},
        {w: "mental", m: "정신의", ex: "Exercise improves mental health.", s: "수능·모의 기출"},
        {w: "quite", m: "꽤, 상당히", ex: "The movie was quite exciting.", s: "수능·모의 기출"},
        {w: "demand", m: "수요; 요구하다", ex: "Demand for the product is high.", s: "수능·모의 기출"},
        {w: "subject", m: "주제; 과목", ex: "Math is my favorite subject.", s: "수능·모의 기출"},
        {w: "fiction", m: "소설, 허구", ex: "She prefers science fiction novels.", s: "수능·모의 기출"},
        {w: "effect", m: "효과, 영향", ex: "The new rule had a positive effect.", s: "수능·모의 기출"},
        {w: "climate", m: "기후", ex: "The climate here is warm and dry.", s: "수능·모의 기출"},
        {w: "direct", m: "직접적인; 지시하다", ex: "Take the most direct route home.", s: "수능·모의 기출"},
        {w: "practice", m: "연습; 관행", ex: "Daily practice improves your skills.", s: "수능·모의 기출"},
        {w: "familiar", m: "익숙한, 친숙한", ex: "This street looks familiar to me.", s: "수능·모의 기출"},
        {w: "survival", m: "생존", ex: "Water is essential for survival.", s: "수능·모의 기출"},
        {w: "readers", m: "독자들", ex: "The book attracted many readers.", s: "수능·모의 기출"},
        {w: "tourism", m: "관광, 관광업", ex: "Tourism boosts the local economy.", s: "수능·모의 기출"},
        {w: "artists", m: "예술가들", ex: "Local artists displayed their work.", s: "수능·모의 기출"},
        {w: "variety", m: "다양성, 종류", ex: "The menu offers a variety of dishes.", s: "수능·모의 기출"},
        {w: "position", m: "위치; 지위", ex: "He holds a high position in the firm.", s: "수능·모의 기출"},
        {w: "degree", m: "정도; 학위; 도", ex: "She earned a degree in biology.", s: "수능·모의 기출"},
        {w: "produce", m: "생산하다", ex: "The factory produces cars.", s: "수능·모의 기출"},
        {w: "patterns", m: "패턴, 양식들", ex: "Scientists study weather patterns.", s: "수능·모의 기출"},
        {w: "model", m: "모형, 모델", ex: "She built a model of the bridge.", s: "수능·모의 기출"},
        {w: "plastic", m: "플라스틱", ex: "Plastic waste pollutes the ocean.", s: "수능·모의 기출"},
        {w: "avoid", m: "피하다", ex: "Try to avoid junk food.", s: "수능·모의 기출"},
        {w: "increase", m: "증가하다; 증가", ex: "Prices continue to increase.", s: "수능·모의 기출"},
        {w: "required", m: "필수의, 요구되는", ex: "A ticket is required for entry.", s: "수능·모의 기출"},
        {w: "original", m: "원래의; 독창적인", ex: "The original plan was much simpler.", s: "수능·모의 기출"},
        {w: "include", m: "포함하다", ex: "The price includes tax and delivery.", s: "수능·모의 기출"},
        {w: "rights", m: "권리들", ex: "Human rights must be protected.", s: "수능·모의 기출"},
        {w: "expected", m: "기대된, 예상된", ex: "The results were better than expected.", s: "수능·모의 기출"},
        {w: "feedback", m: "피드백, 반응", ex: "The teacher gave helpful feedback.", s: "수능·모의 기출"},
        {w: "contrast", m: "대조; 대조하다", ex: "In contrast, summers here are hot.", s: "수능·모의 기출"},
        {w: "indeed", m: "정말로, 실제로", ex: "The trip was indeed unforgettable.", s: "수능·모의 기출"},
        {w: "methods", m: "방법들", ex: "Teachers use various methods.", s: "수능·모의 기출"},
        {w: "images", m: "이미지, 영상들", ex: "The book has colorful images.", s: "수능·모의 기출"},
        {w: "cases", m: "경우들; 사례", ex: "In some cases, exceptions apply.", s: "수능·모의 기출"},
        {w: "managers", m: "관리자들", ex: "The managers held a meeting today.", s: "수능·모의 기출"},
        {w: "access", m: "접근; 이용하다", ex: "Students have access to the library.", s: "수능·모의 기출"},
        {w: "cause", m: "원인; 야기하다", ex: "Smoking can cause serious illness.", s: "수능·모의 기출"},
        {w: "related", m: "관련된", ex: "These two problems are closely related.", s: "수능·모의 기출"},
        {w: "conflict", m: "갈등, 충돌", ex: "They resolved the conflict peacefully.", s: "수능·모의 기출"},
        {w: "freedom", m: "자유", ex: "Freedom of speech is a basic right.", s: "수능·모의 기출"},
        {w: "schedule", m: "일정, 시간표", ex: "Check the schedule before you leave.", s: "수능·모의 기출"},
        {w: "suddenly", m: "갑자기", ex: "Suddenly, the lights went out.", s: "수능·모의 기출"},
        {w: "either", m: "둘 중 하나; ~도 또한", ex: "You can take either road.", s: "수능·모의 기출"},
        {w: "extended", m: "연장된, 확장된", ex: "They took an extended vacation.", s: "수능·모의 기출"},
        {w: "systems", m: "체계, 시스템들", ex: "Computer systems can fail sometimes.", s: "수능·모의 기출"},
        {w: "general", m: "일반적인", ex: "In general, exercise improves mood.", s: "수능·모의 기출"},
        {w: "forward", m: "앞으로", ex: "Please step forward one at a time.", s: "수능·모의 기출"},
        {w: "provided", m: "제공된; ~라는 조건으로", ex: "Lunch will be provided for free.", s: "수능·모의 기출"},
        {w: "legal", m: "법적인, 합법적인", ex: "He sought legal advice.", s: "수능·모의 기출"},
        {w: "highly", m: "매우, 대단히", ex: "She is a highly skilled doctor.", s: "수능·모의 기출"},
        {w: "roles", m: "역할들", ex: "Everyone has different roles in the team.", s: "수능·모의 기출"},
        {w: "visual", m: "시각의", ex: "The lesson used many visual aids.", s: "수능·모의 기출"},
        {w: "creating", m: "창조하는 것", ex: "She enjoys creating new recipes.", s: "수능·모의 기출"},
        {w: "amount", m: "양, 총액", ex: "A large amount of rain fell.", s: "수능·모의 기출"},
        {w: "receive", m: "받다", ex: "You will receive a reply soon.", s: "수능·모의 기출"},
        {w: "current", m: "현재의; 흐름", ex: "The current situation is stable.", s: "수능·모의 기출"},
        {w: "reach", m: "도달하다; 닿다", ex: "We finally reached the top.", s: "수능·모의 기출"},
        {w: "audience", m: "청중, 관객", ex: "The audience clapped loudly.", s: "수능·모의 기출"},
        {w: "studies", m: "연구들; 공부하다", ex: "Recent studies confirm the theory.", s: "수능·모의 기출"},
        {w: "relieved", m: "안도한", ex: "She was relieved to hear the news.", s: "수능·모의 기출"},
        {w: "allows", m: "허락하다, 가능하게 하다", ex: "This pass allows free entry.", s: "수능·모의 기출"},
        {w: "politics", m: "정치", ex: "She is interested in politics.", s: "수능·모의 기출"},
        {w: "beliefs", m: "신념, 믿음들", ex: "People have different beliefs.", s: "수능·모의 기출"},
        {w: "defined", m: "정의된", ex: "The rules are clearly defined.", s: "수능·모의 기출"},
        {w: "appears", m: "나타나다, ~처럼 보이다", ex: "She appears calm under pressure.", s: "수능·모의 기출"},
        {w: "memory", m: "기억, 추억", ex: "I have a happy memory of that day.", s: "수능·모의 기출"},
        {w: "balance", m: "균형", ex: "It is hard to balance work and life.", s: "수능·모의 기출"},
        {w: "involved", m: "관련된, 참여한", ex: "Many people were involved in the project.", s: "수능·모의 기출"},
        {w: "creative", m: "창의적인", ex: "She has a creative mind.", s: "수능·모의 기출"},
        {w: "artistic", m: "예술적인", ex: "He has real artistic talent.", s: "수능·모의 기출"},
        {w: "theory", m: "이론", ex: "The theory is hard to prove.", s: "수능·모의 기출"},
        {w: "features", m: "특징들", ex: "The phone has many new features.", s: "수능·모의 기출"},
        {w: "probably", m: "아마도", ex: "It will probably rain tomorrow.", s: "수능·모의 기출"},
        {w: "manner", m: "방식; 태도", ex: "He answered in a polite manner.", s: "수능·모의 기출"},
        {w: "resource", m: "자원", ex: "Time is a valuable resource.", s: "수능·모의 기출"},
        {w: "multiple", m: "다수의, 여러 개의", ex: "The test has multiple questions.", s: "수능·모의 기출"},
        {w: "tasks", m: "과제, 업무들", ex: "She finished all her tasks early.", s: "수능·모의 기출"},
        {w: "career", m: "경력, 직업", ex: "She built a successful career in law.", s: "수능·모의 기출"},
        {w: "efforts", m: "노력들", ex: "Her efforts finally paid off.", s: "수능·모의 기출"},
        {w: "improve", m: "향상시키다, 개선하다", ex: "Practice will improve your skills.", s: "수능·모의 기출"},
        {w: "rarely", m: "드물게, 좀처럼 ~않는", ex: "He rarely eats fast food.", s: "수능·모의 기출"},
        {w: "distance", m: "거리", ex: "The town is a short distance away.", s: "수능·모의 기출"},
        {w: "search", m: "검색; 찾다", ex: "They searched everywhere for the keys.", s: "수능·모의 기출"},
        {w: "clothing", m: "의류, 옷", ex: "Warm clothing is needed in winter.", s: "수능·모의 기출"},
        {w: "himself", m: "그 자신", ex: "He fixed the bike himself.", s: "수능·모의 기출"},
        {w: "selected", m: "선택된", ex: "She was selected for the team.", s: "수능·모의 기출"},
        {w: "suggests", m: "제안하다, 시사하다", ex: "The data suggests a clear pattern.", s: "수능·모의 기출"},
        {w: "belief", m: "믿음, 신념", ex: "He has a strong belief in justice.", s: "수능·모의 기출"},
        {w: "finding", m: "발견, 결과", ex: "The main finding surprised the team.", s: "수능·모의 기출"},
        {w: "ties", m: "유대, 관계; 넥타이", ex: "Family ties are very important.", s: "수능·모의 기출"},
        {w: "actions", m: "행동들", ex: "Actions speak louder than words.", s: "수능·모의 기출"},
        {w: "desire", m: "욕구, 열망", ex: "She has a strong desire to learn.", s: "수능·모의 기출"},
        {w: "topic", m: "주제, 화제", ex: "Choose an interesting topic for the essay.", s: "수능·모의 기출"},
        {w: "pleasure", m: "즐거움, 기쁨", ex: "It's a pleasure to meet you.", s: "수능·모의 기출"},
        {w: "causes", m: "원인들; 야기하다", ex: "Poor diet causes many diseases.", s: "수능·모의 기출"},
        {w: "aged", m: "나이 든; ~세의", ex: "The program helps aged citizens.", s: "수능·모의 기출"},
        {w: "bored", m: "지루한", ex: "The students looked bored in class.", s: "수능·모의 기출"},
        {w: "contact", m: "연락; 접촉하다", ex: "Please contact us by email.", s: "수능·모의 기출"},
        {w: "fashion", m: "패션, 유행", ex: "She follows the latest fashion.", s: "수능·모의 기출"},
        {w: "theme", m: "주제, 테마", ex: "The party had a beach theme.", s: "수능·모의 기출"},
        {w: "serve", m: "제공하다, 봉사하다", ex: "They serve lunch at noon.", s: "수능·모의 기출"},
        {w: "active", m: "활동적인, 적극적인", ex: "He leads an active lifestyle.", s: "수능·모의 기출"},
        {w: "ancient", m: "고대의", ex: "We explored the ancient ruins.", s: "수능·모의 기출"},
        {w: "image", m: "이미지, 형상", ex: "The image was very clear.", s: "수능·모의 기출"},
        {w: "details", m: "세부사항들", ex: "Please check the details carefully.", s: "수능·모의 기출"},
        {w: "fixed", m: "고정된; 고쳤다", ex: "The price is fixed and cannot change.", s: "수능·모의 기출"},
        {w: "progress", m: "진전, 발전", ex: "She made great progress this year.", s: "수능·모의 기출"},
        {w: "maintain", m: "유지하다", ex: "It's hard to maintain good habits.", s: "수능·모의 기출"},
        {w: "caused", m: "야기했다", ex: "The storm caused heavy damage.", s: "수능·모의 기출"},
        {w: "annual", m: "연례의, 매년의", ex: "The company held its annual meeting.", s: "수능·모의 기출"},
        {w: "style", m: "방식, 스타일", ex: "She has a unique writing style.", s: "수능·모의 기출"},
        {w: "valuable", m: "귀중한, 가치 있는", ex: "This is valuable advice.", s: "수능·모의 기출"},
        {w: "relative", m: "상대적인; 친척", ex: "His success is a relative concept.", s: "수능·모의 기출"},
        {w: "consumer", m: "소비자", ex: "Consumer demand drives production.", s: "수능·모의 기출"},
        {w: "privacy", m: "사생활, 프라이버시", ex: "Everyone deserves some privacy.", s: "수능·모의 기출"},
        {w: "outcome", m: "결과", ex: "The outcome of the game surprised us.", s: "수능·모의 기출"},
        {w: "setting", m: "환경, 배경; 설정", ex: "The story has a rural setting.", s: "수능·모의 기출"},
        {w: "vision", m: "시력; 비전, 통찰", ex: "The leader had a clear vision.", s: "수능·모의 기출"},
        {w: "effort", m: "노력", ex: "Success requires great effort.", s: "수능·모의 기출"},
        {w: "respond", m: "대응하다, 응답하다", ex: "Please respond to the email soon.", s: "수능·모의 기출"},
        {w: "towards", m: "~쪽으로", ex: "She ran towards the finish line.", s: "수능·모의 기출"},
    ],
    hard: [
        {w: "context", m: "맥락, 문맥", ex: "Understand the word in its context.", s: "수능·모의 기출"},
        {w: "perspective", m: "관점, 시각", ex: "Try to see it from her perspective.", s: "수능·모의 기출"},
        {w: "potential", m: "잠재력; 잠재적인", ex: "She has great potential as a leader.", s: "수능·모의 기출"},
        {w: "aspects", m: "측면, 양상들", ex: "Consider all aspects of the plan.", s: "수능·모의 기출"},
        {w: "creativity", m: "창의성", ex: "Art class encourages creativity.", s: "수능·모의 기출"},
        {w: "perception", m: "인식, 지각", ex: "Color affects our perception of taste.", s: "수능·모의 기출"},
        {w: "concept", m: "개념", ex: "Time is a difficult concept to explain.", s: "수능·모의 기출"},
        {w: "necessity", m: "필요성, 필수품", ex: "Water is a basic necessity of life.", s: "수능·모의 기출"},
        {w: "respondents", m: "응답자들", ex: "Most respondents agreed with the plan.", s: "수능·모의 기출"},
        {w: "moral", m: "도덕적인; 교훈", ex: "The story teaches a moral lesson.", s: "수능·모의 기출"},
        {w: "capacity", m: "용량; 능력", ex: "The hall has a large seating capacity.", s: "수능·모의 기출"},
        {w: "increasingly", m: "점점 더", ex: "The world is increasingly connected.", s: "수능·모의 기출"},
        {w: "interaction", m: "상호작용", ex: "Social interaction helps children learn.", s: "수능·모의 기출"},
        {w: "associated", m: "관련된, 연관된", ex: "Smoking is associated with cancer.", s: "수능·모의 기출"},
        {w: "organisms", m: "유기체, 생물들", ex: "Tiny organisms live in the soil.", s: "수능·모의 기출"},
        {w: "significant", m: "중요한, 상당한", ex: "The study showed significant results.", s: "수능·모의 기출"},
        {w: "evolution", m: "진화", ex: "Darwin proposed the theory of evolution.", s: "수능·모의 기출"},
        {w: "significance", m: "중요성, 의미", ex: "The event had great historical significance.", s: "수능·모의 기출"},
        {w: "ecosystem", m: "생태계", ex: "Pollution damages the ocean ecosystem.", s: "수능·모의 기출"},
        {w: "ethical", m: "윤리적인", ex: "The company follows ethical standards.", s: "수능·모의 기출"},
        {w: "external", m: "외부의", ex: "External factors affect the results.", s: "수능·모의 기출"},
        {w: "indifferent", m: "무관심한", ex: "He seemed indifferent to the news.", s: "수능·모의 기출"},
        {w: "basis", m: "근거, 기반", ex: "They meet on a weekly basis.", s: "수능·모의 기출"},
        {w: "engage", m: "참여시키다, 관여하다", ex: "The game engages young learners.", s: "수능·모의 기출"},
        {w: "technological", m: "기술적인", ex: "Technological progress is rapid today.", s: "수능·모의 기출"},
        {w: "rational", m: "이성적인, 합리적인", ex: "He made a rational decision.", s: "수능·모의 기출"},
        {w: "nonverbal", m: "비언어적인", ex: "Gestures are a form of nonverbal communication.", s: "수능·모의 기출"},
        {w: "identity", m: "정체성, 신원", ex: "Culture shapes our identity.", s: "수능·모의 기출"},
        {w: "extent", m: "정도, 범위", ex: "To some extent, he was right.", s: "수능·모의 기출"},
        {w: "frequency", m: "빈도, 주파수", ex: "The frequency of storms is rising.", s: "수능·모의 기출"},
        {w: "diverse", m: "다양한", ex: "The city has a diverse population.", s: "수능·모의 기출"},
        {w: "necessarily", m: "반드시, 필연적으로", ex: "Expensive doesn't necessarily mean better.", s: "수능·모의 기출"},
        {w: "biological", m: "생물학적인", ex: "They study biological processes.", s: "수능·모의 기출"},
        {w: "transit", m: "수송, 대중교통", ex: "The city improved its public transit.", s: "수능·모의 기출"},
        {w: "critical", m: "비판적인; 중대한", ex: "Critical thinking helps solve problems.", s: "수능·모의 기출"},
        {w: "cognitive", m: "인지의, 인식의", ex: "Puzzles improve cognitive skills.", s: "수능·모의 기출"},
        {w: "knowledge", m: "지식", ex: "Reading widens your knowledge of the world.", s: "수능·모의 기출"},
        {w: "percentage", m: "비율, 백분율", ex: "A large percentage of students passed the exam.", s: "수능·모의 기출"},
        {w: "particular", m: "특정한, 특별한", ex: "He has no particular reason for leaving.", s: "수능·모의 기출"},
        {w: "attention", m: "주의, 관심", ex: "Please pay attention to the teacher.", s: "수능·모의 기출"},
        {w: "individual", m: "개인; 개별적인", ex: "Each individual has unique talents.", s: "수능·모의 기출"},
        {w: "performance", m: "수행; 공연, 성과", ex: "Her performance on stage was amazing.", s: "수능·모의 기출"},
        {w: "themselves", m: "그들 자신", ex: "They built the house themselves.", s: "수능·모의 기출"},
        {w: "understanding", m: "이해", ex: "Mutual understanding prevents conflicts.", s: "수능·모의 기출"},
        {w: "development", m: "발전, 개발", ex: "Economic development improved living standards.", s: "수능·모의 기출"},
        {w: "environment", m: "환경", ex: "Pollution harms the environment.", s: "수능·모의 기출"},
        {w: "individuals", m: "개인들", ex: "Different individuals have different opinions.", s: "수능·모의 기출"},
        {w: "emotional", m: "감정적인, 정서적인", ex: "She gave an emotional speech at graduation.", s: "수능·모의 기출"},
        {w: "experiences", m: "경험들", ex: "Travel broadens our experiences.", s: "수능·모의 기출"},
        {w: "scientific", m: "과학적인", ex: "The theory has scientific evidence.", s: "수능·모의 기출"},
        {w: "community", m: "공동체, 지역사회", ex: "The whole community joined the cleanup.", s: "수능·모의 기출"},
        {w: "therefore", m: "그러므로", ex: "It rained; therefore, we stayed inside.", s: "수능·모의 기출"},
        {w: "available", m: "이용 가능한", ex: "The room is available for booking.", s: "수능·모의 기출"},
        {w: "situation", m: "상황", ex: "He handled the difficult situation calmly.", s: "수능·모의 기출"},
        {w: "communication", m: "의사소통", ex: "Good communication builds strong teams.", s: "수능·모의 기출"},
        {w: "political", m: "정치의", ex: "The debate covered many political issues.", s: "수능·모의 기출"},
        {w: "particularly", m: "특히", ex: "She is particularly good at math.", s: "수능·모의 기출"},
        {w: "technology", m: "기술, 과학기술", ex: "Technology has transformed education.", s: "수능·모의 기출"},
        {w: "necessary", m: "필요한", ex: "It is necessary to book in advance.", s: "수능·모의 기출"},
        {w: "participants", m: "참가자들", ex: "All participants received a certificate.", s: "수능·모의 기출"},
        {w: "resources", m: "자원들", ex: "Natural resources should be used wisely.", s: "수능·모의 기출"},
        {w: "production", m: "생산", ex: "Car production increased last year.", s: "수능·모의 기출"},
        {w: "population", m: "인구", ex: "The city's population keeps growing.", s: "수능·모의 기출"},
        {w: "education", m: "교육", ex: "Quality education opens many doors.", s: "수능·모의 기출"},
        {w: "conditions", m: "조건, 상태들", ex: "Weather conditions were poor today.", s: "수능·모의 기출"},
        {w: "competition", m: "경쟁, 대회", ex: "There is fierce competition for jobs.", s: "수능·모의 기출"},
        {w: "relationship", m: "관계", ex: "They have a close relationship.", s: "수능·모의 기출"},
        {w: "influence", m: "영향; 영향을 주다", ex: "Parents strongly influence their children.", s: "수능·모의 기출"},
        {w: "environmental", m: "환경의", ex: "We support environmental protection.", s: "수능·모의 기출"},
        {w: "traditional", m: "전통적인", ex: "We enjoyed a traditional Korean meal.", s: "수능·모의 기출"},
        {w: "opportunity", m: "기회", ex: "This job is a great opportunity.", s: "수능·모의 기출"},
        {w: "including", m: "~을 포함하여", ex: "Everyone came, including the manager.", s: "수능·모의 기출"},
        {w: "customers", m: "고객들", ex: "The store treats customers kindly.", s: "수능·모의 기출"},
        {w: "importance", m: "중요성", ex: "He stressed the importance of sleep.", s: "수능·모의 기출"},
        {w: "behaviors", m: "행동들", ex: "Healthy behaviors prevent disease.", s: "수능·모의 기출"},
        {w: "historical", m: "역사적인", ex: "We visited a historical monument.", s: "수능·모의 기출"},
        {w: "effective", m: "효과적인", ex: "Exercise is an effective way to relax.", s: "수능·모의 기출"},
        {w: "typically", m: "전형적으로, 보통", ex: "The bus typically arrives on time.", s: "수능·모의 기출"},
        {w: "successful", m: "성공적인", ex: "The event was very successful.", s: "수능·모의 기출"},
        {w: "researchers", m: "연구자들", ex: "Researchers found surprising results.", s: "수능·모의 기출"},
        {w: "considered", m: "고려된, 여겨지는", ex: "He is considered a great leader.", s: "수능·모의 기출"},
        {w: "especially", m: "특히", ex: "I love fruit, especially apples.", s: "수능·모의 기출"},
        {w: "developed", m: "발달한; 개발했다", ex: "They developed a new medicine.", s: "수능·모의 기출"},
        {w: "materials", m: "재료들, 자료", ex: "We gathered materials for the project.", s: "수능·모의 기출"},
        {w: "additional", m: "추가의", ex: "There is no additional charge.", s: "수능·모의 기출"},
        {w: "frequently", m: "자주, 빈번히", ex: "He frequently visits his grandmother.", s: "수능·모의 기출"},
        {w: "audiences", m: "청중, 관객들", ex: "The show attracted large audiences.", s: "수능·모의 기출"},
        {w: "differences", m: "차이점들", ex: "We should respect our differences.", s: "수능·모의 기출"},
        {w: "challenges", m: "도전, 과제들", ex: "Life is full of challenges.", s: "수능·모의 기출"},
        {w: "situations", m: "상황들", ex: "We must adapt to new situations.", s: "수능·모의 기출"},
        {w: "application", m: "지원(서); 응용", ex: "She submitted her job application.", s: "수능·모의 기출"},
        {w: "disappointed", m: "실망한", ex: "She was disappointed with the result.", s: "수능·모의 기출"},
        {w: "advantage", m: "이점, 장점", ex: "Speaking English is a big advantage.", s: "수능·모의 기출"},
        {w: "consumers", m: "소비자들", ex: "Consumers prefer cheaper products.", s: "수능·모의 기출"},
        {w: "increasing", m: "증가하는", ex: "There is increasing demand for jobs.", s: "수능·모의 기출"},
        {w: "decisions", m: "결정들", ex: "Leaders make important decisions.", s: "수능·모의 기출"},
        {w: "organization", m: "조직, 단체", ex: "He works for a charity organization.", s: "수능·모의 기출"},
        {w: "essential", m: "필수적인", ex: "Sleep is essential for good health.", s: "수능·모의 기출"},
        {w: "management", m: "관리, 경영", ex: "Time management is a useful skill.", s: "수능·모의 기출"},
        {w: "processes", m: "과정들", ex: "The brain processes information quickly.", s: "수능·모의 기출"},
        {w: "expression", m: "표현; 표정", ex: "Art is a form of self expression.", s: "수능·모의 기출"},
        {w: "conversation", m: "대화", ex: "We had a long conversation.", s: "수능·모의 기출"},
        {w: "relationships", m: "관계들", ex: "Strong relationships take time.", s: "수능·모의 기출"},
        {w: "recognize", m: "알아보다, 인정하다", ex: "I didn't recognize her at first.", s: "수능·모의 기출"},
        {w: "unfortunately", m: "불행하게도", ex: "Unfortunately, the show was canceled.", s: "수능·모의 기출"},
        {w: "registration", m: "등록", ex: "Registration closes on Friday.", s: "수능·모의 기출"},
        {w: "industrial", m: "산업의", ex: "This is an industrial area.", s: "수능·모의 기출"},
        {w: "practical", m: "실용적인", ex: "She gave practical advice.", s: "수능·모의 기출"},
        {w: "competitive", m: "경쟁적인", ex: "The job market is very competitive.", s: "수능·모의 기출"},
        {w: "delighted", m: "기뻐하는", ex: "She was delighted with the gift.", s: "수능·모의 기출"},
        {w: "following", m: "다음의, 따르는", ex: "Read the following passage carefully.", s: "수능·모의 기출"},
        {w: "according", m: "~에 따르면", ex: "According to the report, sales rose.", s: "수능·모의 기출"},
        {w: "confidence", m: "자신감, 신뢰", ex: "She spoke with great confidence.", s: "수능·모의 기출"},
        {w: "temperature", m: "온도, 기온", ex: "The temperature dropped sharply at night.", s: "수능·모의 기출"},
        {w: "classical", m: "고전의, 클래식의", ex: "She enjoys classical music.", s: "수능·모의 기출"},
        {w: "relatively", m: "비교적", ex: "The test was relatively easy.", s: "수능·모의 기출"},
        {w: "literature", m: "문학", ex: "He studies English literature.", s: "수능·모의 기출"},
        {w: "functions", m: "기능들; 작동하다", ex: "The heart functions like a pump.", s: "수능·모의 기출"},
        {w: "impossible", m: "불가능한", ex: "Nothing is impossible if you try.", s: "수능·모의 기출"},
        {w: "similarly", m: "마찬가지로, 비슷하게", ex: "Similarly, plants need sunlight.", s: "수능·모의 기출"},
        {w: "challenge", m: "도전, 과제", ex: "Learning a new language is a challenge.", s: "수능·모의 기출"},
        {w: "characters", m: "등장인물들; 성격", ex: "The novel has memorable characters.", s: "수능·모의 기출"},
        {w: "employees", m: "직원들", ex: "The company hired new employees.", s: "수능·모의 기출"},
        {w: "financial", m: "재정의, 금융의", ex: "He gave sound financial advice.", s: "수능·모의 기출"},
        {w: "absolutely", m: "절대적으로, 완전히", ex: "You are absolutely right.", s: "수능·모의 기출"},
        {w: "international", m: "국제적인", ex: "She works for an international company.", s: "수능·모의 기출"},
        {w: "developing", m: "발전하는, 개발도상의", ex: "Many developing countries need aid.", s: "수능·모의 기출"},
        {w: "participate", m: "참여하다", ex: "Everyone can participate in the event.", s: "수능·모의 기출"},
        {w: "increased", m: "증가했다", ex: "Sales increased last month.", s: "수능·모의 기출"},
        {w: "practices", m: "관행, 관습들", ex: "Farming practices vary by region.", s: "수능·모의 기출"},
        {w: "environments", m: "환경들", ex: "Animals adapt to their environments.", s: "수능·모의 기출"},
        {w: "sincerely", m: "진심으로", ex: "I sincerely apologize for the delay.", s: "수능·모의 기출"},
        {w: "structure", m: "구조", ex: "The essay has a clear structure.", s: "수능·모의 기출"},
        {w: "interests", m: "관심사, 이익들", ex: "We share similar interests.", s: "수능·모의 기출"},
    ],
};
